<?php
//$result = date_default_timezone_set('Asia/Tokyo');
//session_start();
//$dbh = null;
//connect_DBH($dbh);
//mb_regex_encoding("UTF-8");

// データベース接続 その２ 
//function connect_DBH(&$dbh) {
//	try{
//		$dbh = new PDO(PDO_DSN2, DB_USER, DB_PASSWD2);
//		$dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
//	}catch (PDOException $e){
//		//$err_msg = 'Connection failed: ' . $e->getMessage();
//		//exit($err_msg);
//		exit('Connection failed');
//	}
//}

?>
